# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='saved_by',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
