# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireme', '0002_auto_20180110_0106'),
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
